### ISSUE TITLE
Ship turns way too slowly and jitterily.

### ISSUE THREAD

**Issue by ErikBoesen** [BrainiacMainiac/bolides#1]

**Comment by nichosta** [comment]
Fine, I shall increase the turnamount to 10 degrees.

**Comment by ErikBoesen** [comment]
But then it will be more jittery. We want it smooth.

On 6/1/15, Nicholas Costa notifications@github.com wrote:

> Closed #1.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/BrainiacMainiac/bolides/issues/1#event-319171524

## 

Thanks!
Erik Boesen http://erikboesen.com

The information contained in this e-mail message, and any files
transmitted with it, is confidential and may be legally privileged.
It is intended only for the use of the individuals or entities named above.
If the reader of this message is not the intended recipient,
or the employee or agent responsible to deliver it to the intended
recipient, you are hereby notified that any dissemination, distribution
or forwarding of this e-mail message is strictly prohibited. If you have
received this e-mail message in error, please notify the sender and
make a pilgrimage to Mt. Fuji, where you must sacrifice the contents
of this message in fire to whichever gods you feel appropriate.
Thank you for your cooperation.

**Comment by nichosta** [comment]
There's no pleasing you, is there? How fast should it turn, then?

**Comment by ErikBoesen** [comment]
Quickly, but smoothly. So make it rotate at greater frequency but a lower
amount.

Thanks!
Erik Boesen http://erikboesen.com

The information contained in this e-mail message, and any files
transmitted with it, is confidential and may be legally privileged.
It is intended only for the use of the individuals or entities named above.
If the reader of this message is not the intended recipient,
or the employee or agent responsible to deliver it to the intended
recipient, you are hereby notified that any dissemination, distribution
or forwarding of this e-mail message is strictly prohibited. If you have
received this e-mail message in error, please notify the sender and
make a pilgrimage to Mt. Fuji, where you must sacrifice the contents
of this message in fire to whichever gods you feel appropriate.
Thank you for your cooperation.

**Comment by nichosta** [comment]
Fix'd
