### ISSUE TITLE
When space bar is held down, bullet will repeatedly return to ship.

### ISSUE THREAD

**Issue by ErikBoesen** [BrainiacMainiac/bolides#3]
Should wait until it has left the screen until it can be refired. Either that, or there can be multiple bullets, and an ammo gauge can be displayed as part of the HUD.

**Comment by nichosta** [comment]
It was like that originally. I could put it back to that.

**Comment by nichosta** [comment]
Or would you prefer an ammo gauge?

**Comment by ErikBoesen** [comment]
I think an ammo gauge would be good. Regardless, the bullet should always
finish its trip to the edge of the screen.

**Comment by nichosta** [comment]
Fixed, still a glitch, but it's different.
